[workspace]
channels = ["conda-forge"]
name = "chatlog"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
go = ">=1.25.7,<2"
c-compiler = ">=1.11.0,<2"
wget = ">=1.25.0,<2"
uv = ">=0.10.0,<0.11"
